import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, readFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  GROK_IMAGE_TOOL,
  describeGeneratedImage,
  isImageGenerationItem,
  saveGeneratedImage,
} from "../src/imagegen.mjs";

const jpeg = Buffer.concat([Buffer.from([255, 216, 255, 224]), Buffer.alloc(2048, 7)]);
const png = Buffer.concat([
  Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
  Buffer.alloc(1024, 3),
]);

const item = (bytes, extra = {}) => ({
  id: "ig_abcdef_call-12345678-0",
  type: "image_generation_call",
  status: "completed",
  result: bytes.toString("base64"),
  ...extra,
});

test("recognises a completed generation and nothing else", () => {
  assert.equal(isImageGenerationItem(item(jpeg)), true);
  assert.equal(isImageGenerationItem({ type: "image_generation_call" }), false);
  assert.equal(isImageGenerationItem({ type: "message", result: "x" }), false);
  assert.equal(isImageGenerationItem(null), false);
});

test("writes the bytes to a private file and names it by format", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "imagegen-"));
  const saved = saveGeneratedImage(item(jpeg), { dir, now: 0 });
  assert.equal(saved.extension, "jpg");
  assert.equal(saved.bytes, jpeg.length);
  assert.ok(readFileSync(saved.file).equals(jpeg));
  assert.equal(statSync(saved.file).mode & 0o777, 0o600);
  assert.equal(statSync(dir).mode & 0o777, 0o700);

  const asPng = saveGeneratedImage(item(png), { dir, now: 1 });
  assert.equal(asPng.extension, "png");
  assert.notEqual(asPng.file, saved.file, "two generations must not collide");
});

test("the description tells the model where the file is and what made it", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "imagegen-"));
  const generated = item(jpeg, { prompt: "a red circle on white" });
  const saved = saveGeneratedImage(generated, { dir, now: 0 });
  const text = describeGeneratedImage(generated, saved);
  assert.match(text, /generated by Grok/);
  assert.ok(text.includes(saved.file));
  assert.match(text, /JPG, 2 KB/);
  assert.match(text, /Prompt used: "a red circle on white"/);

  // A generation with no prompt echoed back must still describe the file.
  const bare = describeGeneratedImage(item(jpeg), saved);
  assert.ok(bare.includes(saved.file));
  assert.ok(!bare.includes("Prompt used"));
});

test("the declared tool is the shape the proxy expects", () => {
  assert.deepEqual(GROK_IMAGE_TOOL, { type: "image_generation" });
});

test("bytes in an unrecognised format are still saved, just not misnamed", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "imagegen-"));
  const odd = Buffer.from("not an image at all", "utf8");
  const saved = saveGeneratedImage(item(odd), { dir, now: 2 });
  assert.equal(saved.extension, "bin");
  assert.ok(readFileSync(saved.file).equals(odd));

  const webp = Buffer.concat([Buffer.from("RIFF", "ascii"), Buffer.alloc(64)]);
  assert.equal(saveGeneratedImage(item(webp), { dir, now: 3 }).extension, "webp");
});
