import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

// Codex offers no image generation tool to this provider — 263 tools arrive and
// none of them generates an image — so its imagegen skill falls back to the
// OpenAI Python CLI. That puts the picture on a different vendor than the
// thinking. Grok generates server-side when the request carries this tool, so
// the bridge declares it directly and Codex never has to execute anything.
export const GROK_IMAGE_TOOL = Object.freeze({ type: "image_generation" });

export const DEFAULT_IMAGE_DIR = path.join(
  homedir(),
  ".local/share/codex-grok-bridge/generated-images",
);

const SIGNATURES = [
  [Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), "png"],
  [Buffer.from([255, 216, 255]), "jpg"],
  [Buffer.from("RIFF", "ascii"), "webp"],
];

function extensionFor(bytes) {
  for (const [magic, extension] of SIGNATURES)
    if (bytes.subarray(0, magic.length).equals(magic)) return extension;
  return "bin";
}

export function isImageGenerationItem(item) {
  return Boolean(
    item &&
      typeof item === "object" &&
      item.type === "image_generation_call" &&
      typeof item.result === "string" &&
      item.result.length > 0,
  );
}

/**
 * Write a generated image to disk and describe where it went.
 *
 * The bytes arrive inline on the stream; Codex has nowhere to put them. Saving
 * under the bridge's own directory keeps `~/.codex` untouched and leaves the
 * model free to move the file into the workspace with its normal tools, which
 * is what Codex's own image workflow does anyway.
 */
export function saveGeneratedImage(item, options = {}) {
  const dir = options.dir ?? DEFAULT_IMAGE_DIR;
  const bytes = Buffer.from(item.result, "base64");
  const extension = extensionFor(bytes);
  const stamp = (options.now ?? Date.now()).toString(36);
  const suffix = String(item.id ?? "").slice(-8).replace(/[^A-Za-z0-9]/g, "") || "image";
  const file = path.join(dir, `grok-${stamp}-${suffix}.${extension}`);
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  writeFileSync(file, bytes, { mode: 0o600 });
  return { file, bytes: bytes.length, extension, alpha: hasAlphaChannel(bytes) };
}

/**
 * Whether the file can carry transparency at all. PNG says so in its IHDR
 * colour type: 4 is greyscale+alpha, 6 is RGBA.
 */
export function hasAlphaChannel(bytes) {
  const isPng = bytes.subarray(0, 8).equals(SIGNATURES[0][0]);
  if (!isPng || bytes.length < 26) return false;
  const colorType = bytes[25];
  return colorType === 4 || colorType === 6;
}

export function describeGeneratedImage(item, saved) {
  const kb = Math.max(1, Math.round(saved.bytes / 1024));
  const prompt =
    typeof item.prompt === "string" && item.prompt.trim()
      ? ` Prompt used: "${item.prompt.trim()}".`
      : "";
  // Grok returns JPEG even when asked for a transparent PNG, and paints a
  // checkerboard into the picture so it looks cut out. Saying plainly that the
  // file has no alpha stops that being reported to the user as transparency.
  const alpha = saved.alpha
    ? " It has an alpha channel."
    : ` This format carries no alpha channel, so the background is opaque —` +
      ` do not describe it as transparent or cut out, even if it looks that way.`;
  return (
    `[Image generated by Grok and saved to ${saved.file} ` +
    `(${saved.extension.toUpperCase()}, ${kb} KB).${alpha}${prompt} ` +
    `Move or copy it into the workspace if the user wants it there, and tell them the path.]`
  );
}
